[build]
  node_version = "14"
  command = "npm install firebase && npm install && npm run build"  # Your build command
  publish = "public"  # Directory to publish (modify this based on your project)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200